import "./global.css"
import { Inter } from "next/font/google"

export const metadata = {
  title: "Welcome to keepr",
  description: "Generated by create-nx-workspace"
}

const inter = Inter({
  subsets: ["latin"],
  display: "swap"
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
