import { Inter } from "next/font/google"

import { cn } from "@/lib/utils"
import QueryClientProvider from "@/components/providers/query-client"

import "./global.css"

export const metadata = {
  title: "Welcome to keepr",
  description: "Generated by create-nx-workspace"
}

const inter = Inter({
  subsets: ["latin"],
  display: "swap"
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "min-h-screen")}>
        <QueryClientProvider>{children}</QueryClientProvider>
      </body>
    </html>
  )
}
